name: FFHI Gluon Build

on:
  workflow_dispatch:
  push:

env:
  GLUON_REF: d2a9cc369a32dd1c1b5ffb9ac7a452d78457043d

jobs:
  define_matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.versions.outputs.targets }}
    steps:
      - name: Checkout Gluon Release
        uses: actions/checkout@v4
        with:
          repository: freifunk-gluon/gluon
          ref: ${{ env.GLUON_REF }}
          path: './'
      - name: Fill Target Matrix
        id: versions
        run: |
          mkdir site
          touch site/site.mk
          TARGETS=$( make list-targets | tr "\n" " " | sed 's/ /\", \"/g' )
          echo "targets=[\"${TARGETS%???}]" >> "$GITHUB_OUTPUT"

  build:
    needs: define_matrix
    strategy:
      matrix:
        version: ${{ fromJSON(needs.define_matrix.outputs.versions) }}
    runs-on: ubuntu-latest
    steps:
      run: echo "build goes here"
          
  push_artifacts_to_server:
    needs: build
    uses: ./.github/workflows/push_artifacts.yml
