name: Push artifacts to autoupdate server

on:
  workflow_dispatch:
  push:

jobs:
  push-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Query list of artifacts
        run: |
          curl -s -L \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ffhi/ffhi-site/actions/artifacts > artifacts.json
      - name: Checkout ffhi-site
        uses: actions/checkout@v4
        with:
          repository: ffhi/ffhi-site
          ref: ${{ 'dev/push-artifacts-action' }}
          path: './'
      - name: Download artifacts
        run: |
          python3 ffhi-site/.github/scripts/download_artifacts.py ${{secrets.GITHUB_TOKEN}}
      - name: ls
        run: ls
      - name: Save SSH key to file 
        run: 'echo "$SSH_KEY" > keyfile'
        env:
          SSH_KEY: ${{secrets.NETCUP_SSH_PRIVATE_KEY}}
      - name: Prepare SSH connection
        run: |
          cat keyfile
          chmod 400 keyfile
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan firmware.freifunk-hildesheim.de >> ~/.ssh/known_hosts
      - name: Test SSH connection
        run: |
          ssh -i keyfile root@firmware.freifunk-hildesheim.de ls
