name: Push artifacts to autoupdate server

on:
  workflow_dispatch:
  push:

jobs:
  push-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Save SSH key to file 
        run: 'echo "$SSH_KEY" > keyfile'
        shell: bash
        env:
          SSH_KEY: ${{secrets.NETCUP_SSH_PRIVATE_KEY}}
      - name: Test SSH connection
        run: |
          cat keyfile
          chmod 400 keyfile
          ssh -i keyfile root@firmware.freifunk-hildesheim.de ls
