name: Push artifacts to autoupdate server

on:
  workflow_dispatch:
  workflow_run:
    workflows: [FFHI Gluon Build]
    types:
      - completed

env:
  URL_FIRMWARE: firmware.freifunk-hildesheim.de
  CADDY_FOLDER: /opt/docker/caddy/data/www-data/firmware/testing

jobs:
  push-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ffhi-site
        uses: actions/checkout@v4
        with:
          repository: ffhi/ffhi-site
          ref: ${{ 'dev/push-artifacts-action' }}
          path: './'
      - name: Query list of artifacts
        run: |
          curl -s -L \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ffhi/ffhi-site/actions/artifacts > artifacts.json
      - name: Download artifacts
        run: |
          mv .github/scripts/download_artifacts.py ./
          python3 download_artifacts.py ${{secrets.GITHUB_TOKEN}}
      - name: Save SSH key to file 
        run: 'echo "$SSH_KEY" > keyfile'
        env:
          SSH_KEY: ${{secrets.NETCUP_SSH_PRIVATE_KEY}}
      - name: Prepare SSH connection
        run: |
          chmod 400 keyfile
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan ${{env.URL_FIRMWARE}} >> ~/.ssh/known_hosts
      - name: Push files to firmware server
        run: |
          ssh -i keyfile root@${{env.URL_FIRMWARE}} 'rm -rf ${{env.CADDY_FOLDER}} && mkdir ${{env.CADDY_FOLDER}}'
          scp -i keyfile *.zip root@${{env.URL_FIRMWARE}}:${{env.CADDY_FOLDER}}
          ssh -i keyfile root@${{env.URL_FIRMWARE}} 'cd ${{env.CADDY_FOLDER}} && unzip "*.zip"'
          ssh -i keyfile root@${{env.URL_FIRMWARE}} 'rm ${{env.CADDY_FOLDER}}/*.zip'
