name: Push artifacts to autoupdate server

on:
  workflow_dispatch:
  push:

jobs:
  push-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt install jq
      - name: Query list of artifacts
        run: |
          curl -s -L \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ffhi/ffhi-site/actions/artifacts | jq '.artifacts[].archive_download_url' > artifacts.txt
      - name: Read artifacts
        run: |
          cat artifacts.txt       
      - name: Download artifacts
        run: |
          curl -s -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ffhi/ffhi-site/actions/artifacts/2627348586/zip > artifact.zip
      - name: ls
        run: unzip artifact.zip && ls
      - name: Save SSH key to file 
        run: 'echo "$SSH_KEY" > keyfile'
        env:
          SSH_KEY: ${{secrets.NETCUP_SSH_PRIVATE_KEY}}
      - name: Prepare SSH connection
        run: |
          cat keyfile
          chmod 400 keyfile
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan firmware.freifunk-hildesheim.de >> ~/.ssh/known_hosts
      - name: Test SSH connection
        run: |
          ssh -i keyfile root@firmware.freifunk-hildesheim.de ls
